### ISSUE TITLE
I.E E.G

### ISSUE THREAD

**Issue by blksith0** [Galts-Gulch/avarice#1]
In one of the comments for the trade pair, you wrote "i.e." when it should be "e.g."

**Comment by RealJohnGalt** [comment]
Thank you, I'll fix that up shortly. I've been too busy recently to do anything with this.

**Comment by RealJohnGalt** [comment]
This instance was unintentionally fixed as a part of 6742343265b618ca639d5d6f5abcbe2bc1ce23ea

There are more instances of this issue throughout the project, so I'll close the issue when they're all fixed.
