### ISSUE TITLE
OKcoin websocket uses python2 but avarice uses asyncio which is python3

### ISSUE THREAD

**Issue by ghost** [Galts-Gulch/avarice#12]
The OKCOIN websocket example included in this package uses the websocket python2 only library.  However, the avarice python scripts utilize asyncio which is a python3 only library.

If I try to run any of the avarice scripts using python 3, I get an error due the websocket library being non existant for python 3.

And if I try to run the avarice scripts using python 2, I get an error because asyncio is not on python2.

How do I use this?

**Comment by RealJohnGalt** [comment]
Hi m0rfious,
I'm not sure what operating system or distribution you're on, so that info would definitely help.

Both "websockets" and "websocket-client" are available for python3 (and websockets is only available for python3). I recommend using pip for python3 to install the dependencies (named pip3 from most packages). This may be done with "pip3 install websockets websocket-client"

**Comment by ghost** [comment]
Thanks man! I was doing pip3.4 install websocket and getting syntax errors...wasnt aware websockets websocket-client was the package to install.

Sorry for the trouble - you can delete this issue if you want!  Thank you for all the hard work!

**Comment by RealJohnGalt** [comment]
No problem. Those are actually two packages. "websockets" and "websocket" are also two entirely different packages (only one of which we use).

I'll leave this open for a bit in case there are other issues you run into. I'll also be sure to edit the documentation to include pip3 install lines which could be copy/pasted on most configurations.

**Comment by ghost** [comment]
Hate to keep the thread going and dont know if I am doing something silly again, but I run python3 avarice.py and I seem to be stuck at connecting to the OKCoin websocket.  The sqllite db seems to have generated properly, but no data is coming through.  I am using default configuration, but have verified TradePair='btc_cny' in genconfig.py.

Python 3.4, OSX Yosemite.

**Comment by RealJohnGalt** [comment]
Hey m0rfious, this is a bug on the current 3.0 beta. It waits whatever the set candle size is before starting the first candle. See #8 . For instance if the candle size is 15 minutes, then it will say that for 15 minutes before starting. I'll fix this shortly.

**Comment by ghost** [comment]
Thanks again! I set the candle size to 1 min to see if I can get it to update and I've got it up and running.
