### ISSUE TITLE
First run

### ISSUE THREAD

**Issue by ppls12** [Galts-Gulch/avarice#2]
Hi,

thanks for sharing Avarice! I hope this is the correct place for my question:

I tried to run it under Ubuntu 14.04 and get this shell output:

$ python avarice.py
Traceback (most recent call last):
  File "avarice.py", line 5, in <module>
    import indicators
  File "/home/mike/Arbeitsfläche/ava/indicators.py", line 5, in <module>
    import loggerdb as ldb
  File "/home/mike/Arbeitsfläche/ava/loggerdb.py", line 7, in <module>
    import exchangelayer
  File "/home/mike/Arbeitsfläche/ava/exchangelayer.py", line 8, in <module>
    import okcoin_api
  File "/home/mike/Arbeitsfläche/ava/okcoin_api.py", line 11, in <module>
    import urllib.error
ImportError: No module named error

Do you know any advice?

Thanks

**Comment by RealJohnGalt** [comment]
Hi ppls12,
I know this is a very late response, but it looks like you're using python 2 there instead of python 3. Please run python --version to verify, and check that python3 is installed. If so, you can run it with "python3" instead of "python" without changing defaults.

**Comment by ppls12** [comment]
thx, for your response. Yes it worked, I really used python 2!
 

Gesendet: Montag, 12. Januar 2015 um 04:10 Uhr
Von: "John Galt" notifications@github.com
An: Galts-Gulch/avarice avarice@noreply.github.com
Cc: ppls12 ppls@gmx.de
Betreff: Re: [avarice] First run (#2)

Hi ppls12,
I know this is a very late response, but it looks like you're using python 2 there instead of python 3. Please run python --version to verify, and check that python3 is installed. If so, you can run it with "python3" instead of "python" without changing defaults.

**Comment by RealJohnGalt** [comment]
Glad it worked out for you. Since this issue's taken care of, I'm going to close it. If you find any other issues, feel free to open a new issue here.
