### ISSUE TITLE
New OKCoin API

### ISSUE THREAD

**Issue by sandzja** [Galts-Gulch/avarice#3]
User authentication is not working properly with new OKcoin API. 
Example of new version here: https://github.com/OKCoin/rest/blob/master/Python/okcoin.py

**Comment by RealJohnGalt** [comment]
Thank you, I'll start working on adding in the new spot API shortly. Apologies for the late response, I've been to busy to work on this recently.

**Comment by RealJohnGalt** [comment]
This is now fixed :+1:

**Comment by RealJohnGalt** [comment]
There are some issues with this current API still, I jumped the gun. I'm switching to the new OKCoin github published code which uses SNI.
